name: Build release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Update version number
      run: npm version --allow-same-version --no-git-tag-version ${{ github.ref_name }}

    - name: Install dependencies
      run: npm install

    - name: Build and package
      run: npx @vscode/vsce package

    - name: Attach vsix
      uses: actions/upload-artifact@v4.0.0
      with:
        name: arcad-ibmi-servers
        path: ./arcad-ibmi-servers*.vsix
      
    - name: Bump version number for next cycle
      run: npm version --no-git-tag-version prerelease --preid snapshot

    - name: Commit version number change
      uses: GuillaumeFalourd/git-commit-push@v1.3
      with:     
        commit_message: Post-release ${{ github.ref_name }} commit
        target_branch: main
