name: Build release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: main

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Update version number
      run: npm version --allow-same-version --no-git-tag-version ${{ github.ref_name }}

    - name: Install dependencies
      run: npm install

    - name: Build and package
      run: npx @vscode/vsce package

    - name: Attach vsix
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        asset_name: arcad-ibmi-servers-${{ github.ref_name }}.vsix
        file: arcad-ibmi-servers-${{ github.ref_name }}.vsix        

    - name: Commit changes and move release tag
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git commit --allow-empty -a -m "Release ${{ github.ref_name }}"
        git tag -f ${{ github.ref_name }}        

    - name: Push changes
      run: git push --tags --force

    - name: Bump version number for next cycle
      run: npm version --no-git-tag-version prerelease --preid snapshot

    - name: Commit version number change
      run: |
        git commit -a -m "Post release build commit"
        git push
